# Generated by Django 3.0.7 on 2020-06-16 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='store.Address'),
        ),
    ]
