# Generated by Django 3.0.7 on 2020-07-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200711_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='path',
        ),
    ]
