# Generated by Django 3.0.7 on 2020-07-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200712_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.FilePathField(path='/Users/xuhua/desktop/online_store/src/store/images/'),
        ),
    ]
