# Generated by Django 3.0.7 on 2020-07-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20200712_0358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
