# Generated by Django 3.0.7 on 2020-07-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.FilePathField(path='/Users/xuhua/desktop/online_store/src/frontend/src/images/'),
        ),
    ]
