# Generated by Django 3.0.7 on 2020-07-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20200712_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.FilePathField(path='/images/'),
        ),
    ]
