# Generated by Django 3.0.7 on 2020-07-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20200713_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
